apiVersion: v1
kind: Service
metadata:
  name: uss-pensions-shiny
spec:
  type: NodePort
  selector:
    app: uss-pensions-shiny
  ports:
    - protocol: TCP
      port: 8011
      targetPort: 3838
      nodePort: 30111
